# agent/steps/06_push.sh — step_push: push + PR creation + verification
# Return: 0=ok, 1=skip iteration, 2=break loop

step_push() {
  cd "$REPO_ROOT"
  git push -u origin "$BRANCH_NAME"

  # ── Post-push verification — ensure all commits are pushed ───────────────
  cd "$REPO_ROOT"
  git fetch origin "$BRANCH_NAME" 2>/dev/null || true
  local LOCAL_HEAD REMOTE_HEAD
  LOCAL_HEAD=$(git rev-parse HEAD)
  REMOTE_HEAD=$(git rev-parse "origin/$BRANCH_NAME" 2>/dev/null) || true
  if [[ -n "$REMOTE_HEAD" && "$LOCAL_HEAD" != "$REMOTE_HEAD" ]]; then
    log "WARN: Local HEAD ($LOCAL_HEAD) != remote ($REMOTE_HEAD). Re-pushing..."
    git push origin "$BRANCH_NAME" 2>/dev/null || true
    git fetch origin "$BRANCH_NAME" 2>/dev/null || true
    REMOTE_HEAD=$(git rev-parse "origin/$BRANCH_NAME" 2>/dev/null) || true
    if [[ "$LOCAL_HEAD" != "$REMOTE_HEAD" ]]; then
      log "ERROR: Still out of sync after re-push for #$TASK_ISSUE. Marking as pend."
      mark_pend "$TASK_ISSUE" "git push 後もローカルとリモートが同期できません"
      cleanup_branch "$BRANCH_NAME"
      sleep "$SLEEP_SECONDS"
      return 1
    fi
  fi

  log "Post-push verification passed: local and remote are in sync."

  # ── Create PR ────────────────────────────────────────────────────────────
  local PR_PREFIX PR_BODY
  PR_PREFIX=$(detect_commit_prefix)
  log "Detected commit prefix: $PR_PREFIX"

  PR_BODY="## Summary

Implements issue #$TASK_ISSUE: $TASK_TITLE

$TASK_DESC

Closes #$TASK_ISSUE

---
Generated by agent/loop.sh"

  PR_URL=$(gh pr create \
    --title "$PR_PREFIX: $TASK_TITLE" \
    --body "$PR_BODY" \
    --base main \
    --head "$BRANCH_NAME" 2>/dev/null) || true

  if [[ -z "$PR_URL" ]]; then
    log "ERROR: Failed to create PR for #$TASK_ISSUE"
    gh issue edit "$TASK_ISSUE" --remove-label "doing" 2>/dev/null || true
    cleanup_branch "$BRANCH_NAME"
    sleep "$SLEEP_SECONDS"
    return 1
  fi

  log "PR created: $PR_URL"

  # ── Post-PR verification — ensure PR diff contains changes ───────────────
  local PR_DIFF_STAT PR_FILE_COUNT
  PR_DIFF_STAT=$(gh pr diff "$PR_URL" --name-only 2>/dev/null) || true
  if [[ -z "$PR_DIFF_STAT" ]]; then
    log "ERROR: PR has no file changes for #$TASK_ISSUE. The PR diff is empty."
    gh pr close "$PR_URL" 2>/dev/null || true
    mark_pend "$TASK_ISSUE" "PRのdiffが空です（変更がコミットされていない可能性があります）"
    cleanup_branch "$BRANCH_NAME"
    sleep "$SLEEP_SECONDS"
    return 1
  fi

  PR_FILE_COUNT=$(echo "$PR_DIFF_STAT" | wc -l | tr -d ' ')
  log "Post-PR verification passed: PR contains changes in $PR_FILE_COUNT file(s)."

  return 0
}
