# agent/steps/06_push.sh — step_push: push + PR creation + verification
# Return: 0=ok, 1=skip iteration, 2=break loop

step_push() {
  cd "$REPO_ROOT"
  git push -u origin "$BRANCH_NAME"

  # ── Post-push verification — ensure all commits are pushed ───────────────
  cd "$REPO_ROOT"
  git fetch origin "$BRANCH_NAME" 2>/dev/null || true
  local LOCAL_HEAD REMOTE_HEAD
  LOCAL_HEAD=$(git rev-parse HEAD)
  REMOTE_HEAD=$(git rev-parse "origin/$BRANCH_NAME" 2>/dev/null) || true
  if [[ -n "$REMOTE_HEAD" && "$LOCAL_HEAD" != "$REMOTE_HEAD" ]]; then
    log "WARN: Local HEAD ($LOCAL_HEAD) != remote ($REMOTE_HEAD). Re-pushing..."
    git push origin "$BRANCH_NAME" 2>/dev/null || true
    git fetch origin "$BRANCH_NAME" 2>/dev/null || true
    REMOTE_HEAD=$(git rev-parse "origin/$BRANCH_NAME" 2>/dev/null) || true
    if [[ "$LOCAL_HEAD" != "$REMOTE_HEAD" ]]; then
      log "ERROR: Still out of sync after re-push for #$TASK_ISSUE. Marking as pend."
      mark_pend "$TASK_ISSUE" "git push 後もローカルとリモートが同期できません"
      cleanup_branch "$BRANCH_NAME"
      sleep "$SLEEP_SECONDS"
      return 1
    fi
  fi

  log "Post-push verification passed: local and remote are in sync."

  # ── Create PR ────────────────────────────────────────────────────────────
  local PR_PREFIX PR_BODY
  PR_PREFIX=$(detect_commit_prefix)
  log "Detected commit prefix: $PR_PREFIX"

  PR_BODY="## Summary

Implements issue #$TASK_ISSUE: $TASK_TITLE

$TASK_DESC

Closes #$TASK_ISSUE

---
Generated by agent/loop.sh"

  PR_URL=$(gh pr create \
    --title "$PR_PREFIX: $TASK_TITLE" \
    --body "$PR_BODY" \
    --base main \
    --head "$BRANCH_NAME" 2>/dev/null) || true

  if [[ -z "$PR_URL" ]]; then
    log "ERROR: Failed to create PR for #$TASK_ISSUE"
    mark_pend "$TASK_ISSUE" "PR作成に失敗しました（差分がない、またはGitHub APIエラーの可能性があります）"
    cleanup_branch "$BRANCH_NAME"
    sleep "$SLEEP_SECONDS"
    return 1
  fi

  log "PR created: $PR_URL"

  # ── Post-PR verification — ensure PR diff contains changes ───────────────
  local PR_DIFF_STAT PR_FILE_COUNT
  PR_DIFF_STAT=$(gh pr diff "$PR_URL" --name-only 2>/dev/null) || true
  if [[ -z "$PR_DIFF_STAT" ]]; then
    log "ERROR: PR has no file changes for #$TASK_ISSUE. The PR diff is empty."
    gh pr close "$PR_URL" 2>/dev/null || true
    mark_pend "$TASK_ISSUE" "PRのdiffが空です（変更がコミットされていない可能性があります）"
    cleanup_branch "$BRANCH_NAME"
    sleep "$SLEEP_SECONDS"
    return 1
  fi

  PR_FILE_COUNT=$(echo "$PR_DIFF_STAT" | wc -l | tr -d ' ')
  log "Post-PR verification passed: PR contains changes in $PR_FILE_COUNT file(s)."

  # ── Content-level diff validation — assess quality beyond empty check ──────
  local VALIDATE_PROMPT FULL_DIFF VALIDATE_INPUT VALIDATE_STDERR VALIDATE_OUTPUT VALIDATE_JSON VERDICT REASONING
  VALIDATE_PROMPT=$(cat "$SCRIPT_DIR/prompts/validate-diff.md")
  FULL_DIFF=$(gh pr diff "$PR_URL" 2>/dev/null || echo "(no diff available)")

  VALIDATE_INPUT="$VALIDATE_PROMPT

## Issue Title

$TASK_TITLE

## PR Diff

\`\`\`diff
$FULL_DIFF
\`\`\`"

  log "Running diff content validation for #$TASK_ISSUE..."
  VALIDATE_STDERR="/tmp/claude/agent-validate-diff-stderr.log"
  VALIDATE_OUTPUT=$(claude -p "$VALIDATE_INPUT" \
    --max-turns "$VALIDATE_DIFF_MAX_TURNS" \
    --max-budget-usd "$MAX_BUDGET_USD" \
    2>"$VALIDATE_STDERR") || true

  # Rate limit check
  if check_rate_limit "$VALIDATE_STDERR"; then
    flag_rate_limit
    gh pr close "$PR_URL" 2>/dev/null || true
    gh issue edit "$TASK_ISSUE" --remove-label "doing" 2>/dev/null || true
    cleanup_branch "$BRANCH_NAME"
    return 2
  fi

  # Parse verdict from output
  VALIDATE_JSON=$(echo "$VALIDATE_OUTPUT" | sed -n '/^```json$/,/^```$/{ /^```/d; p; }')
  VERDICT=$(echo "$VALIDATE_JSON" | jq -r '.verdict' 2>/dev/null || echo "")
  REASONING=$(echo "$VALIDATE_JSON" | jq -r '.reasoning' 2>/dev/null || echo "")

  if [[ "$VERDICT" == "pass" ]]; then
    log "Diff content validation passed for #$TASK_ISSUE: $REASONING"
    return 0
  fi

  if [[ "$VERDICT" == "fail" ]]; then
    log "WARN: Diff content validation failed for #$TASK_ISSUE: $REASONING"
    log "Closing PR and marking issue as needs-split."
    gh pr close "$PR_URL" 2>/dev/null || true
    git push origin --delete "$BRANCH_NAME" 2>/dev/null || true
    mark_needs_split "$TASK_ISSUE"
    cleanup_branch "$BRANCH_NAME"
    sleep "$SLEEP_SECONDS"
    return 1
  fi

  # Could not parse output — treat as pass to avoid blocking
  log "WARN: Could not parse diff validation agent output for #$TASK_ISSUE. Treating as pass."
  return 0
}
