name: 機能リクエスト
description: reownの新機能や改善を提案する
labels: ["enhancement", "agent"]
body:
  - type: input
    id: title_summary
    attributes:
      label: 概要
      description: 機能の短い説明（例：「PRを承認するキーボードショートカットを追加」）
      placeholder: "<動詞> <対象> を <場所> に"
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: ゴール
      description: この機能で何を達成したいですか？期待する結果を記述してください。
      placeholder: |
        この機能が実装された後、ユーザーが何をできるようになるかを記述してください。
        例：「PR詳細ビューで 'a' キーを押してPRを直接承認できるようにする。」
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 背景
      description: なぜこの機能が必要ですか？どんな問題を解決しますか？
      placeholder: |
        現在のペインや制限を記述してください。
        例：「現在、PRを承認するにはブラウザに切り替える必要があり、ローカルファーストのワークフローが中断される。」
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ基準
      description: この機能が完了したと見なすための条件を定義してください。
      placeholder: |
        - [ ] <満たすべき具体的な条件>
        - [ ] 新機能のユニットテストがある
        - [ ] cargo test と cargo clippy が通る
    validations:
      required: true

  - type: dropdown
    id: pillar
    attributes:
      label: ピラー
      description: この機能はどのプロダクトピラーに該当しますか？（docs/INTENT.md参照）
      options:
        - review-support — 影響範囲分析、リスク評価、レビューパターン
        - local-gui — すべてのPRレビューのための統合ローカルインターフェース
        - automation — リスクに基づく自動承認・自動マージ
        - dev-support — タスク提案、ワークツリー作成
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: 推定スコープ
      description: この機能の規模はどのくらいですか？
      options:
        - small — 単一ファイルの変更、独立したロジック
        - medium — 複数ファイル、1モジュール
        - large — モジュール横断、アーキテクチャ変更
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 補足情報
      description: 追加のコンテキスト、モックアップ、参考資料、関連Issue等。
      placeholder: 関連Issue、モックアップ、設計ドキュメントへのリンク。
    validations:
      required: false
