name: Feature Request
description: Propose a new feature or enhancement for reown
labels: ["enhancement", "agent"]
body:
  - type: input
    id: title_summary
    attributes:
      label: Summary
      description: A short, descriptive summary of the feature (e.g. "Add keyboard shortcut to approve PR")
      placeholder: "<action verb> <what> in <where>"
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What should this feature achieve? Describe the desired outcome.
      placeholder: |
        Describe what the user should be able to do after this feature is implemented.
        Example: "Users should be able to approve a PR directly from the PR detail view by pressing 'a'."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Why is this feature needed? What problem does it solve?
      placeholder: |
        Describe the current pain point or limitation.
        Example: "Currently users must switch to the browser to approve PRs, breaking the local-first workflow."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define the conditions that must be met for this feature to be considered complete.
      placeholder: |
        - [ ] <specific condition that must be true>
        - [ ] Unit tests cover the new functionality
        - [ ] cargo test and cargo clippy pass
    validations:
      required: true

  - type: dropdown
    id: pillar
    attributes:
      label: Pillar
      description: Which product pillar does this feature serve? (See docs/INTENT.md)
      options:
        - review-support — impact analysis, risk assessment, review patterns
        - local-gui — unified local interface for all PR reviews
        - automation — auto-approve, auto-merge based on risk
        - dev-support — task suggestions, worktree creation
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Estimated Scope
      description: How large is this feature?
      options:
        - small — single file change, isolated logic
        - medium — multiple files, one module
        - large — cross-module, architectural change
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional context, mockups, references, or related issues.
      placeholder: Links to related issues, mockups, or design docs.
    validations:
      required: false
